apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
  namespace: example-test
spec:
  replicas: 2
  selector:
    matchLabels:
      stack: example
  template:
    metadata:
      labels:
        stack: example
    spec:
      containers:
      - name: example-pod
        image: easybeinggreenuk/example:latest
        imagePullPolicy: Always
        # https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: example-service
  namespace: example-test
spec:
  type: LoadBalancer
  sessionAffinity: None
  selector:
    stack: example
  ports:
  - name : default
    port: 8080
    targetPort: 8080